import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NoteProvider } from "./contexts/NoteContext";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NoteNest",
  description: "Generated by Rahat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NoteProvider>
          <NavBar></NavBar>
          {children}
        </NoteProvider>
      </body>
    </html>
  );
}
